//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net_Entity_Framework_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADRES
    {
        public byte ID { get; set; }
        public string TELEFON { get; set; }
        public byte[] MAIL { get; set; }
        public string ADRES { get; set; }
        public string KONUM { get; set; }
    }
}
